package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	flowstateDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/flowstate/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// FlowstateCreateFixedEvent is the resolver for the flowstateCreateFixedEvent field.
func (r *mutationResolver) FlowstateCreateFixedEvent(ctx context.Context, input model.FlowstateFixedEventInput) (*model.FlowstateFixedEvent, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	req := &flowstateDTO.FixedEventRequest{
		Title:      input.Title,
		StartTime:  input.StartTime,
		EndTime:    input.EndTime,
		DaysOfWeek: input.DaysOfWeek,
		Category:   string(input.Category),
	}
	resp, err := r.CreateFixedEventUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return flowstateFixedEventToModel(resp), nil
}

// FlowstateDeleteFixedEvent is the resolver for the flowstateDeleteFixedEvent field.
func (r *mutationResolver) FlowstateDeleteFixedEvent(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.DeleteFixedEventUC.Execute(ctx, id)
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// FlowstateCreateFlexibleTask is the resolver for the flowstateCreateFlexibleTask field.
func (r *mutationResolver) FlowstateCreateFlexibleTask(ctx context.Context, input model.FlowstateFlexibleTaskInput) (*model.FlowstateFlexibleTask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	req := &flowstateDTO.FlexibleTaskRequest{
		Title:            input.Title,
		DurationMinutes:  input.DurationMinutes,
		FrequencyPerWeek: input.FrequencyPerWeek,
		Constraints:      map[string]any{},
	}
	if input.Priority != nil {
		req.Priority = string(*input.Priority)
	}
	if input.PreferredContext != nil {
		req.PreferredContext = string(*input.PreferredContext)
	}
	if input.Constraints != nil && *input.Constraints != "" {
		_ = json.Unmarshal([]byte(*input.Constraints), &req.Constraints)
	}

	resp, err := r.CreateFlexibleTaskUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return flowstateFlexibleTaskToModel(resp), nil
}

// FlowstateDeleteFlexibleTask is the resolver for the flowstateDeleteFlexibleTask field.
func (r *mutationResolver) FlowstateDeleteFlexibleTask(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.DeleteFlexibleTaskUC.Execute(ctx, id)
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// FlowstateGenerateSchedule is the resolver for the flowstateGenerateSchedule field.
func (r *mutationResolver) FlowstateGenerateSchedule(ctx context.Context, input *model.FlowstateGenerateScheduleInput) (*model.FlowstateSchedulePayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	req := &flowstateDTO.GenerateScheduleRequest{}
	if input != nil && input.WeekIdentifier != nil {
		req.WeekIdentifier = *input.WeekIdentifier
	}

	resp, err := r.GenerateScheduleUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return flowstateScheduleToModel(resp), nil
}

// FlowstateFixedEvents is the resolver for the flowstateFixedEvents field.
func (r *queryResolver) FlowstateFixedEvents(ctx context.Context) ([]*model.FlowstateFixedEvent, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	items, err := r.ListFixedEventsUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	result := make([]*model.FlowstateFixedEvent, 0, len(items))
	for _, item := range items {
		result = append(result, flowstateFixedEventRespToModel(item))
	}
	return result, nil
}

// FlowstateFlexibleTasks is the resolver for the flowstateFlexibleTasks field.
func (r *queryResolver) FlowstateFlexibleTasks(ctx context.Context) ([]*model.FlowstateFlexibleTask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	items, err := r.ListFlexibleTasksUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	result := make([]*model.FlowstateFlexibleTask, 0, len(items))
	for _, item := range items {
		result = append(result, flowstateFlexibleTaskRespToModel(item))
	}
	return result, nil
}

// FlowstateSchedule is the resolver for the flowstateSchedule field.
func (r *queryResolver) FlowstateSchedule(ctx context.Context, week *string) (*model.FlowstateSchedulePayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	weekID := ""
	if week != nil {
		weekID = *week
	}
	resp, err := r.GetScheduleUC.Execute(ctx, weekID)
	if err != nil {
		return nil, mapErr(err)
	}
	if resp == nil {
		return nil, nil
	}
	return flowstateScheduleToModel(resp), nil
}
