package resolver

// helpers.go contains shared helper functions used across resolver files.
// This file is NOT regenerated by gqlgen.

import (
	"time"

	"github.com/google/uuid"
	authDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/auth/dto"
	settingsDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/settings/dto"
	userDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/user/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
)

// mapErr converts domain errors to GraphQL-friendly errors.
func mapErr(err error) error {
	if de, ok := err.(*domainErr.DomainError); ok {
		return de // already has code + message
	}
	return err
}

// authRespToPayload converts an auth DTO response to the GraphQL AuthPayload model.
func authRespToPayload(resp *authDTO.AuthResponse) *model.AuthPayload {
	id, _ := uuid.Parse(resp.User.ID)
	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		ExpiresIn:    int(resp.ExpiresIn),
		User: &model.AuthUser{
			ID:          id,
			Email:       resp.User.Email,
			DisplayName: resp.User.DisplayName,
			AvatarURL:   resp.User.AvatarURL,
			Role:        graphqlRole(resp.User.Role),
		},
	}
}

// profileRespToModel converts a user profile DTO to the GraphQL UserProfile model.
func profileRespToModel(resp *userDTO.UserProfileResponse) *model.UserProfile {
	id, _ := uuid.Parse(resp.ID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	return &model.UserProfile{
		ID:          id,
		Email:       resp.Email,
		DisplayName: resp.DisplayName,
		AvatarURL:   resp.AvatarURL,
		Bio:         resp.Bio,
		Status:      model.UserStatus(toUpperStatus(resp.Status)),
		Role:        graphqlRole(resp.Role),
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}
}

// settingsRespToModel converts a settings DTO to the GraphQL UserSettingsPayload model.
func settingsRespToModel(userID uuid.UUID, resp *settingsDTO.UserSettingsResponse) *model.UserSettingsPayload {
	return &model.UserSettingsPayload{
		ID:              uuid.New(),
		UserID:          userID,
		NotificationsOn: resp.NotificationsOn,
		Theme:           stringToTheme(resp.Theme),
		Language:        resp.Language,
		Timezone:        resp.Timezone,
		UpdatedAt:       time.Now().UTC(),
	}
}

// stringToTheme converts a lowercase theme string to the GraphQL Theme enum.
func stringToTheme(s string) model.Theme {
	switch s {
	case "light":
		return model.ThemeLight
	case "dark":
		return model.ThemeDark
	default:
		return model.ThemeSystem
	}
}

// themeToString converts the GraphQL Theme enum to a lowercase storage string.
func themeToString(t model.Theme) string {
	switch t {
	case model.ThemeLight:
		return "light"
	case model.ThemeDark:
		return "dark"
	default:
		return "system"
	}
}

// graphqlRole converts a lowercase domain role string to the GraphQL UserRole enum.
func graphqlRole(role string) model.UserRole {
	switch role {
	case "admin":
		return model.UserRoleAdmin
	case "moderator":
		return model.UserRoleModerator
	default:
		return model.UserRoleUser
	}
}

// toUpperStatus converts a lowercase domain status string to the uppercase GraphQL value.
func toUpperStatus(status string) string {
	switch status {
	case "active":
		return "ACTIVE"
	case "inactive":
		return "INACTIVE"
	case "suspended":
		return "SUSPENDED"
	default:
		return "ACTIVE"
	}
}
