package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	userDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/user/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UserProfile, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	resp, err := r.UpdateProfileUC.Execute(ctx, &userDTO.UpdateProfileRequest{
		UserID:      userID.String(),
		DisplayName: input.DisplayName,
		AvatarURL:   input.AvatarURL,
		Bio:         input.Bio,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return profileRespToModel(resp), nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.ErrUnauthorized
	}

	if err := r.DeleteAccountUC.Execute(ctx, userID.String()); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.UserProfile, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	resp, err := r.GetProfileUC.Execute(ctx, userID.String())
	if err != nil {
		return nil, mapErr(err)
	}
	return profileRespToModel(resp), nil
}
